[tox]
env_list = lint, smoke
skip_missing_interpreters = true

[testenv:lint]
description = run linting for all MongoDB Compass artifacts
skip_install = true
allowlist_externals =
    tox
commands =
    tox -c compass/tox.ini -e lint
