#!/usr/bin/env bash
# Installation hook for mongodb-compass snap

set -eux
export ETC="${SNAP_COMMON}/etc"
export MONGODB_COMPASS_CONFIG="${ETC}/mongodb-compass.conf"

mkdir -p $ETC

cp -r ${SNAP}/etc/mongodb-compass.conf ${MONGODB_COMPASS_CONFIG}
chmod 644 ${MONGODB_COMPASS_CONFIG}
